"""M1 initial schema — 7 bảng nền của pipeline MTE (Project/Page/TextRegion/OCRResult/TranslationResult/TypesetResult/Job)

Revision ID: 6584b3d32634
Revises: 
Create Date: 2026-08-27 14:19:21.874930
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_m1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_lang', sa.Enum('ja', 'zh', 'en', name='source_lang'), nullable=False),
    sa.Column('target_lang', sa.Enum('vi', name='target_lang'), nullable=False),
    sa.Column('intended_use', sa.Enum('personal', 'study', 'other', name='intended_use'), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('clean_image_path', sa.String(length=1024), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'detecting', 'detected', 'detection_failed', 'ocr_done', 'inpainted', 'inpaint_needs_review', 'translated', 'typeset_done', 'ready_for_export', name='page_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_page_project_order', 'page', ['project_id', 'order'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('detect', 'ocr', 'inpaint', 'translate', 'typeset', 'export', name='job_type'), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_page_id'), 'job', ['page_id'], unique=False)
    op.create_table('text_region',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_w', sa.Float(), nullable=False),
    sa.Column('bbox_h', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('overlap_suspect', sa.Boolean(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'low_confidence', 'confirmed', name='region_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_region_page_id'), 'text_region', ['page_id'], unique=False)
    op.create_table('ocr_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.Enum('manga_ocr', 'paddle_ocr', name='ocr_engine'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ok', 'needs_manual', name='ocr_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['text_region.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    op.create_table('translation_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('engine', sa.Enum('google_fast', 'llm_context', name='translation_engine'), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('token_cost', sa.Integer(), nullable=True),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ok', 'fallback_used', name='translation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['text_region.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    op.create_table('typeset_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('font_family', sa.String(length=255), nullable=True),
    sa.Column('font_size', sa.Float(), nullable=True),
    sa.Column('wrapped_text', sa.Text(), nullable=True),
    sa.Column('padding_ratio', sa.Float(), nullable=True),
    sa.Column('fit_status', sa.Enum('pending', 'fit_ok', 'overflow_warning', name='fit_status'), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['text_region.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('typeset_result')
    op.drop_table('translation_result')
    op.drop_table('ocr_result')
    op.drop_index(op.f('ix_text_region_page_id'), table_name='text_region')
    op.drop_table('text_region')
    op.drop_index(op.f('ix_job_page_id'), table_name='job')
    op.drop_table('job')
    op.drop_index('ix_page_project_order', table_name='page')
    op.drop_table('page')
    op.drop_table('project')
    # Postgres enum type không tự biến mất khi drop table -> phải drop tường minh,
    # nếu không lần `upgrade head` sau sẽ lỗi "type already exists".
    for enum_name in (
        'fit_status',
        'translation_status',
        'translation_engine',
        'ocr_status',
        'ocr_engine',
        'region_status',
        'job_status',
        'job_type',
        'page_status',
        'project_status',
        'intended_use',
        'target_lang',
        'source_lang',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
