"""M8 export chapter — bảng export_job + Page.exported_at

Revision ID: 0002_m8
Revises: 0001_m1
Create Date: 2026-08-28
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '0002_m8'
down_revision = '0001_m1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.Enum('png_single', 'cbz', 'zip', name='export_format'), nullable=False),
    # `job_status` ĐÃ được M1 tạo. Để `sa.Enum(...)` ở đây thì Alembic sẽ CREATE TYPE lần nữa
    # và Postgres báo "type already exists" -> phải dùng create_type=False.
    sa.Column(
        'status',
        postgresql.ENUM(
            'queued', 'running', 'done', 'failed', name='job_status', create_type=False
        ),
        nullable=False,
    ),
    sa.Column('output_path', sa.String(length=1024), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('overflow_warning_count', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('page', sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('page', 'exported_at')
    op.drop_table('export_job')
    # Enum type KHÔNG tự biến mất khi drop table (bài học từ M1) -> phải drop tường minh,
    # nếu không lần `upgrade head` sau sẽ lỗi "type already exists".
    # `job_status` thì KHÔNG được drop: M1 vẫn đang dùng cho bảng `job`.
    op.execute(sa.text('DROP TYPE IF EXISTS export_format'))
