"""M9 batch — bảng batch_run + batch_item

Revision ID: 0003_m9
Revises: 0002_m8
Create Date: 2026-08-28
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '0003_m9'
down_revision = '0002_m8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requested_pipeline', sa.Enum('full_pipeline', 'retry_failed', name='batch_pipeline'), nullable=False),
    sa.Column('translation_engine', postgresql.ENUM('google_fast', 'llm_context', name='translation_engine', create_type=False), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'partial_failed', 'blocked_quota', 'failed', 'cancelled', name='batch_status'), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('completed_pages', sa.Integer(), nullable=False),
    sa.Column('failed_pages', sa.Integer(), nullable=False),
    sa.Column('blocked_pages', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_run_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('page_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'blocked_quota', 'skipped', name='batch_item_status'), nullable=False),
    sa.Column('current_job_id', sa.UUID(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_run_id'], ['batch_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_job_id'], ['job.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_run_id', 'page_id', name='uq_batch_item_run_page')
    )
    op.create_index('ix_batch_item_current_job', 'batch_item', ['current_job_id'], unique=False)
    op.create_index('ix_batch_item_run_status_order', 'batch_item', ['batch_run_id', 'status', 'page_order'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_batch_item_run_status_order', table_name='batch_item')
    op.drop_index('ix_batch_item_current_job', table_name='batch_item')
    op.drop_table('batch_item')
    op.drop_table('batch_run')
    # Enum type KHÔNG tự biến mất khi drop table (bài học từ M1) -> drop tường minh.
    # `translation_engine` thì KHÔNG drop: M5 vẫn đang dùng cho bảng translation_result.
    for ten in ("batch_item_status", "batch_status", "batch_pipeline"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {ten}"))
