"""E13 — thuật ngữ, giọng nhân vật, việc rà soát nhất quán

Revision ID: 0006_e13
Revises: 0005_e12
Create Date: 2026-08-29
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0006_e13'
down_revision = '0005_e12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_voice_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('character_name', sa.Text(), nullable=False),
    sa.Column('character_name_key', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('speech_register', sa.Enum('neutral', 'formal', 'casual', 'childlike', 'rough', 'archaic', 'comic', name='speech_register'), nullable=False),
    sa.Column('vietnamese_pronoun_guidance', sa.Text(), nullable=True),
    sa.Column('tone_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='voice_profile_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'character_name_key', name='uq_voice_project_name')
    )
    op.create_index('ix_voice_project_status', 'character_voice_profile', ['project_id', 'status'], unique=False)
    op.create_table('glossary_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_lang', postgresql.ENUM('ja', 'zh', 'en', name='source_lang', create_type=False), nullable=False),
    sa.Column('target_lang', postgresql.ENUM('vi', name='target_lang', create_type=False), nullable=False),
    sa.Column('source_term', sa.Text(), nullable=False),
    sa.Column('source_term_key', sa.Text(), nullable=False),
    sa.Column('target_term', sa.Text(), nullable=False),
    sa.Column('term_type', sa.Enum('character_name', 'place', 'organization', 'item', 'skill', 'title_rank', 'honorific', 'catchphrase', 'general_term', name='term_type'), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('usage_note', sa.Text(), nullable=True),
    sa.Column('prohibited_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'rejected', 'archived', name='glossary_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_lang', 'source_term_key', name='uq_glossary_project_term')
    )
    op.create_index('ix_glossary_project_status', 'glossary_entry', ['project_id', 'status'], unique=False)
    op.create_table('consistency_review_task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('glossary_entry_id', sa.UUID(), nullable=True),
    sa.Column('voice_profile_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.Enum('glossary_missing', 'glossary_variant', 'prohibited_variant', 'voice_consistency_suspect', 'llm_suggestion', name='consistency_task_type'), nullable=False),
    sa.Column('status', sa.Enum('open', 'accepted', 'rejected', 'stale', 'resolved_no_change', name='consistency_task_status'), nullable=False),
    sa.Column('current_text_snapshot', sa.Text(), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['glossary_entry_id'], ['glossary_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['text_region.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['character_voice_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'task_type', 'glossary_entry_id', 'voice_profile_id', 'snapshot_hash', name='uq_consistency_task_idem', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_consistency_project_status_type', 'consistency_review_task', ['project_id', 'status', 'task_type'], unique=False)
    op.create_index('ix_consistency_region', 'consistency_review_task', ['region_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_consistency_region', table_name='consistency_review_task')
    op.drop_index('ix_consistency_project_status_type', table_name='consistency_review_task')
    op.drop_table('consistency_review_task')
    op.drop_index('ix_glossary_project_status', table_name='glossary_entry')
    op.drop_table('glossary_entry')
    op.drop_index('ix_voice_project_status', table_name='character_voice_profile')
    op.drop_table('character_voice_profile')
    # Enum type KHÔNG tự biến mất khi drop table (bài học từ M1) -> drop tường minh.
    # `source_lang`/`target_lang` thì KHÔNG drop: M1 vẫn đang dùng cho bảng project.
    for ten in (
        "consistency_task_status",
        "consistency_task_type",
        "voice_profile_status",
        "speech_register",
        "glossary_status",
        "term_type",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {ten}"))
